spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testProject
    username: user
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  liquibase:
    enabled: true
    change-log: db/changelog.yaml

  jpa:
    properties.hibernate:
      #     ddl-auto: create
      #     hbm2ddl.auto: validate
      show_sql: true
      format_qsl: true

logging:
  level:
    root: info
  file:
    name: test.log
    path: /
